export const SET_MODAL = "SET_MODAL";
export const NEW_OUTFIT_PRESS = "NEW_OUTFIT_PRESS";
export const NEW_CLOTHING_ITEM_PRESS = "NEW_CLOTHING_ITEM_PRESS";
export const CLOSE_BOTTOM_SHEET = "CLOSE_BOTTOM_SHEET";
