export const CREATE_INIT = "CREATE_INIT";
export const SET_NAV_FROM = "SET_NAV_FROM";
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";
export const CLOTHING_ITEM_CREATION_SUCCESS = "CLOTHING_ITEM_CREATION_SUCCESS";
export const CLEAR_SUCCESS_MESSAGE = "CLEAR_SUCCESS_MESSAGE";
export const LOADING = "LOADING";
